language: php
php:
  - 7.0
  - 7.1  
  
before_script:
  - phpenv rehash

script:
    - composer install --prefer-dist
    - vendor/bin/phpunit -c tests/phpUnit/phpunit.xml --no-coverage 

matrix:
    allow_failures:

notifications:
    on_success: never
    on_failure: always
